### ISSUE TITLE
An assertion has failed: expected non-nil TF state during Create; required to obtain ID

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#128]
See https://travis-ci.com/pulumi/pulumi-cloud/builds/67549324.

```
[ mi/pulumi-cloud/aws/tests/unit ]     + aws:ec2/natGateway:NatGateway: (create)
[ mi/pulumi-cloud/aws/tests/unit ]         [urn=urn:pulumi:p-it-travis-job-unit::unittests::aws:ec2/natGateway:NatGateway::pulumi-p-it-travi-global-nat-1]
[ mi/pulumi-cloud/aws/tests/unit ]         allocationId: "eipalloc-6249714c"
[ mi/pulumi-cloud/aws/tests/unit ]         subnetId    : "subnet-eaa25d90"
[ mi/pulumi-cloud/aws/tests/unit ]         tags        : {
[ mi/pulumi-cloud/aws/tests/unit ]             Name: "pulumi-p-it-travi-global-nat-1"
[ mi/pulumi-cloud/aws/tests/unit ]         }
[ mi/pulumi-cloud/aws/tests/unit ] @ updating........
[ mi/pulumi-cloud/aws/tests/unit ] info: panic: fatal: An assertion has failed: expected non-nil TF state during Create; required to obtain ID
[ mi/pulumi-cloud/aws/tests/unit ] info: 
[ mi/pulumi-cloud/aws/tests/unit ] info: goroutine 3720 [running]:
[ mi/pulumi-cloud/aws/tests/unit ] info: github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.failfast(0xc420024b40, 0x57)
[ mi/pulumi-cloud/aws/tests/unit ] info: 	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/failfast.go:11 +0xf3
[ mi/pulumi-cloud/aws/tests/unit ] info: github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract.Assertf(0xc420521d00, 0x2b95d8b, 0x3e, 0x0, 0x0, 0x0)
[ mi/pulumi-cloud/aws/tests/unit ] info: 	/home/travis/gopath/src/github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi/pkg/util/contract/assert.go:21 +0x13d
[ mi/pulumi-cloud/aws/tests/unit ] info: github.com/pulumi/pulumi-aws/vendor/github.com/pulumi/pulumi-terraform/pkg/tfbridge.(*Provider).Create(0xc4202cfad0, 0x458d600, 0xc4201c17d0, 0xc420773d80, 0xc4202cfad0, 0x0, 0x0)
...
```

**Comment by lukehoban** [comment]
Confirmed that this is still an issue.

**Comment by ellismg** [comment]
I hit this during the azure hackathon and I believe it is now fixed in the 0.18.0 azure provider, for the case described above (the azure storage blob without a type case).

**Comment by jen20** [comment]
I'm still of the opinion that every time we encounter this is a bug upstream, and we have no real recourse other than to fail, and try to fix upstream. Does anyone have a workaround with a better story?

**Comment by ellismg** [comment]
> Does anyone have a workaround with a better story?

I think that you are right.  Do you think it would at least be possible to augment the assert message here to include the type (and maybe name from the URN) for resource that was being created when we failed? I think it would make these sorts of things easier to track down (since it might at least give you an indication of where in your program to look.  It may also make it easier for us to help folks diagnose this issue, without having to start capturing at log level 9.

**Comment by jen20** [comment]
Yes, we can definitely make this less scary, and include more useful information in the error message. I'll sort that out in a PR shortly.

**Comment by jen20** [comment]
@ellismg I've improved the error messages in #372 to include the URN of the affected resource in each case. Since this particular case is always indicative of a bug upstream, I've left this case as an assertion rather than a standard error, however.
