### ISSUE TITLE
Ad support for string-valued properties to optionally auto-JSON.stringify from some strong type

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#129]
We would like to define JSON schema in overlays and then allow users to pass instances of that type as an alternative to passing a string input.

This will require new support in `pulumi-terraform` to automatically `JSON.stringify` the object values passed in to such properties.

**Comment by joeduffy** [comment]
Duplicate of https://github.com/pulumi/pulumi-terraform/issues/10.
