### ISSUE TITLE
Consider putting PEP-484 type hints on Python generated classes and functions 

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi-terraform#168]
IDEs are pretty good at figuring out what types need to go where but they can be helped out significantly by the presence of PEP-484 type comments. We could significantly improve the Python IDE experience by doing this.

VS Code in particular is aware of these comments and will use them to provide improved code completion.

**Comment by lukehoban** [comment]
@swgillespie We already implemented a fair bit of type hinting in the new Python3 pulumi SDK.  What is remaining at this stage?

**Comment by swgillespie** [comment]
@lukehoban Python resources that tfgen emits look sort of like this:

```python
class SomeResource(pulumi.CustomResource):
    def __init__(self, name, props, opts=None):
        __props__ = {}
        __props__["foo"] = props["foo"]
        ...
        CustomResource.__init__(self, "foo:bar:baz", __props__, opts)
```

Ideally, we'd emit something like this:
```python
class SomeResource(pulumi.CustomResource):
    foo: Output[str] # <- note this
    """
    Docstring for Foo
    """

    def __init__(self, name, props, opts=None):
        __props__ = {}
        __props__["foo"] = props["foo"]
        ...
        CustomResource.__init__(self, "foo:bar:baz", __props__, opts)
```

The additional type hint at the root of the class greatly improves the IDE experience here. Also, as we venture into documentation territory for Python, we will need to place docstrings on the properties that we expose so that documentation generators can pick them up.
