### ISSUE TITLE
Python generated code should use not use implicit relative imports anywhere

### ISSUE THREAD

**Issue by swgillespie** [pulumi/pulumi-terraform#184]
See https://github.com/pulumi/pulumi/issues/1541. This is a Python 3 compat hazard.

**Comment by yapith-suplari** [comment]
I got pass the relative import issues, then there's the basestring used everywhere issues. Then I wonder if someone is already tracking all the back-compat issues. Is there an umbrella issue that captures all kinds python 3 compat issues? I think it's useful to improve community visibility, so we can help track them and/or fix them.

**Comment by swgillespie** [comment]
I've been tracking them here: https://github.com/pulumi/pulumi/issues/1535. I've also been using the `language/python3` tag to track individual issues.

**Comment by swgillespie** [comment]
Fixed by https://github.com/pulumi/pulumi-terraform/pull/270.
