### ISSUE TITLE
IdentityPoolRoleAttachment roles TypeScript definition is wrong

### ISSUE THREAD

**Issue by Octirke** [pulumi/pulumi-terraform#186]
Disclaimer : I don't fully understand how the whole Pulumi project is organized and how the node sdk is generated from the terraform bridge. However, I think that typing related issues are somewhat related to the generation step so this is why I'm posting the issue here.

In `identityPoolRoleAttachment.d.ts` you have the roles keys is defined like this :

```typescript
readonly roles?: pulumi.Input<{
        [key: string]: {
            authenticated?: pulumi.Input<string>;
            unauthenticated?: pulumi.Input<string>;
        };
    }>;
```

A valid definition in user code can look like this :
```typescript
roles: {'any-string-key':{unauthenticated:'iam-role-here'}}
```

But this is not considered valid by Pulumi as pointed by `pulumini preview` output :

```bash
Diagnostics:
  global: global
    error: aws:cognito/identityPoolRoleAttachment:IdentityPoolRoleAttachment resource 'thom-test-pulumi-identity-role-attachment' has a problem: roles (roles): '' expected type 'string', got unconvertible type 'map[string]interface {}'
```

This is considered valid by Pulumi but it's not conform according to the TypeScript type definition :
```typescript
roles: {'any-string-key':{unauthenticated:'iam-role-here'}}
```

PS : Pulumi is awesome 😄

**Comment by jen20** [comment]
Hi @Octirke! I'm investigating this now, sorry for the delay in responding on this issue! It looks to me like some other changes to the Terraform bridge have broken how this is interpreted. According to the original Terraform schema, it should be:

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_cognito_identity_pool_roles_attachment.go#L93-L111

However, we are currently (as of the changes adopted in pulumi/pulumi-aws#306) producing this type definition, which is (IMO) incorrect:

```
readonly roles: pulumi.Input<{
    authenticated?: pulumi.Input<string>,
    unauthenticated?: pulumi.Input<string>
}>;
```

We should in fact be projecting this as we were previously:

```
readonly roles?: pulumi.Input<{
        [key: string]: {
            authenticated?: pulumi.Input<string>;
            unauthenticated?: pulumi.Input<string>;
        };
    }>;
```

I'm not sure yet why this changed, or why it was failing originally - this will take some archaeology across the bridge and the Terraform provider. I'll comment back here when I have something more concrete.

**Comment by lukehoban** [comment]
Cc @pgavlin who has assured me repeatedly that although unintuitive given how the TF schemas looks, our projection of this is now “correct” relative to what TF actually does (and how as a result TF providers are currently implemented). I believe the change came from 
https://github.com/pulumi/pulumi-terraform/pull/236. 

My guess is that that change actually already fixed the original issue reported above?

**Comment by pgavlin** [comment]
> My guess is that that change actually already fixed the original issue reported above?

I believe so, yes. @jen20 there is a bug in TF that unintentionally treats maps of resources quite strangely; please see the reasoning in #236.
