### ISSUE TITLE
Need a way to validate up-stack impact for PRs

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-terraform#200]
We've had a rash of issues recently where we'll make a change to `pulumi-terraform` and land it, then when updating the downstream providers (e.g. aws) we'll find some issue either in the generated code or runtime behavior.

It would be ideal if we could have automation that given a PR in pulumi-terraform would use it to rebuild all the providers and run their tests.  For each provider we'd like to be able to see two things:

1. The diff in the generated provider source
2. The results of the existing integration tests.

This is especially important as more and more external folks work on pulumi-terraform where it is unreasonable to expect they'll run a large matrix of tests across multiple cloud providers.

**Comment by joeduffy** [comment]
If we land something, great, but I think we have our hands full with Billing, etc.

**Comment by stack72** [comment]
So this is already taken care of - as part of pulumi-terraform, we look at the impact on AWS, GCP and Azure to make sure it still works as expected
