### ISSUE TITLE
Author overlays inside pack folder?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#21]
The current `tfgen` model places overlay sources outside the `pack` folder, and copies them into the `pack` file during generation.  Some overlays may depend on resources defined in generated code though, and those dependencies are not available in the source location, so editors/linters/etc. will show errors.

The experience here was better in previous iterations where we authored the overlays in the pack folder.  But we can't do that in the current model as the `index.ts` files are autogenerated, so anything added in the pack file cannot be made visible from the package.

We could move back to authoring overlays in the pack folder but still listing them in the `resources.go` file so that they get added to the right `index.ts` files.

**Comment by joeduffy** [comment]
@CyrusNajmabadi did this last sprint.
