### ISSUE TITLE
Allow equivalent to `namePrefix` for all resources

### ISSUE THREAD

**Issue by jen20** [pulumi/pulumi-terraform#210]
Often it is desirable to customise the format of an automatically-generated resource name, either to meet the conventional format while not affecting the name component of the URN, or for some other purpose.

Terraform provides a `name_prefix` field on some resources (`aws_role` for example), which is imported into the Pulumi SDK. However, this field is unusable since it conflicts with `name`, which is automatically set by Pulumi.

It would be useful to have a first-class `namePrefix` construct that can be used to separate the cloud provider resource name generation from the URN name of resources.

**Comment by pgavlin** [comment]
> However, this field is unusable since it conflicts with name, which is automatically set by Pulumi.

This does not appear to be the case any longer: some time ago we fixed a bug s.t. we no longer set defaults if they would conflict with user-specified properties.
