### ISSUE TITLE
resource ABC has a problem: "tag.0.key": required field is not set

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#222]
On initial preview, passing a computed array to a `tags` proeprty fails check:

```
    readonly tags?: pulumi.Input<pulumi.Input<{
        key: pulumi.Input<string>;
        propagateAtLaunch: pulumi.Input<boolean>;
        value: pulumi.Input<string>;
    }>[]>;
```

Full repro at: https://gist.github.com/jen20/ccc91ab961843babf93b119fe67e1938

This only appears to impact first preview.

**Comment by lukehoban** [comment]
@pgavlin Is this the same issue that was fixed with https://github.com/pulumi/pulumi-terraform/pull/255?

**Comment by pgavlin** [comment]
I'll bet it is, yes.

**Comment by pgavlin** [comment]
Confirmed. This is now fixed.
