### ISSUE TITLE
Allow tfbridge to elide TF resources.

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-terraform#233]
e.g. for deprecated resources such as `template_file`.

**Comment by joeduffy** [comment]
Are we sure we want to remove these? IIRC, you get deprecation warnings, which is your signal to move away from using these. But in the period between deprecation and removal, I think we still want them to be available, especially for folks converting from existing working HCL scripts?

**Comment by joeduffy** [comment]
P. S. https://github.com/pulumi/pulumi-terraform/pull/195 was definitely a :+1:, I am responding specifically to removing deprecated members, but maybe something else was intended.

**Comment by Frassle** [comment]
You could keep them. I'm not sure if entire resources can be marked "removed" in terraform, if so might still need a way to skip whole resources at some point. File and CloudinitConfig as resources are very old though, from before terraform had data sources, so thought I'd point them out.

**Comment by lukehoban** [comment]
For now, let's just let these show up as deprecated so that we don't strictly block usage.  We may come back and create options to truly remove these in the future - but for now it seems safer to not strictly block.
