### ISSUE TITLE
Document the process for updating Terraform providers

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform#265]
AFAIK, we haven't written down the process for updating Terraform providers. We should.

This includes:

* The process for updating forks from upstream
* The process for patching their dependency lock files (if any)
* The process for ingesting those versions into the Pulumi package repos
* The process for updating the packages based on the new code

**Comment by jen20** [comment]
I've written this process up now the tooling and process is stabilised and confirmed working across a wide range of providers (only GCP is missing). An initial draft is here: 
https://gist.github.com/jen20/478714e9cec698d970903f7a3f26557e - where is the best place for this to live?

**Comment by jen20** [comment]
This is now on the pulumi-Terraform wiki. I’ll open PRs to each of the relevant providers’ README and CONTRIBUTING files.

**Comment by jen20** [comment]
This is now complete.
