### ISSUE TITLE
Enable deploying Terraform modules

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform#274]
It would be quite useful as an intermediate step in the transition from Terraform to Pulumi, if one could allocate Terraform modules from within otherwise-Pulumi programs (in TypeScript, Python, etc). This would allow organizations still wanting to maintain Terraform modules -- either for legacy purposes, or perhaps even on a go-forward basis for infrastructure teams -- incrementally adopt Pulumi.

**Comment by cristi-** [comment]
Joe, do you mean "allocate Terraform modules from within otherwise-Pulumi programs" to express "export terraform modules from Pulumi stacks" ? This would be interesting to have, especially when companies don't want to change from TF over night.

Thanks!

**Comment by jen20** [comment]
I'd suggest that we could close this out since we now have `RemoteStateReference` (in this repository) - it would be a lot of work to meet the same semantics as Terraform in every case.
