### ISSUE TITLE
Do a better job of extracting docs for nested fields

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform#317]
We previously ignored nested fields altogether. Recently, we began emitting them into the docs. What would be better is to attribute what top-level property they belong to, and augment that property's documentation -- or, perhaps better, if we had dedicated nominal types for the nested structures, generating documentation for those instead.

**Comment by lukehoban** [comment]
What is remaining here now that https://github.com/pulumi/pulumi-terraform/pull/456 has been merged?

We clearly have to address https://github.com/pulumi/docs/issues/1467, but that is already being tracked separately - so is there anything else this issue is tracking?

**Comment by lukehoban** [comment]
@justinvp Closing this out - but if there are additional follow-ups needed feel free to open new issues.
