### ISSUE TITLE
Properties marked as Computed, Optional and ForceNew cause unexpected Replaces

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#329]
We've had two reports of issues where replaces are happening unexpectedly:
* https://github.com/pulumi/pulumi-azure/issues/182
* https://github.com/pulumi/pulumi-aws/issues/451

In both cases, a property is triggering a replace even though it was not specified in the Pulumi program either before or after the update.  This happens because the property is `Computed`, and gets a value assigned as an output, but is also `Optional` so is allowed to not be present in the Pulumi program, but because there is not a default (or that default is not the same as the computed value), this leads to a diff.  In the problematic cases, this property is also `ForceNew`, leading to a replacement being proposed, even though no change is actually needed.

In the case of https://github.com/pulumi/pulumi-azure/issues/182, we have confirmed that the same scenario does not lead to a replacement in Terraform, which suggests that this is not just a bug in the providers (although the resolution of https://github.com/pulumi/pulumi-aws/issues/451 suggested that that issue might just be a bug in the provider).

**Comment by lukehoban** [comment]
In the case of https://github.com/pulumi/pulumi-azure/issues/182, the [property](https://github.com/terraform-providers/terraform-provider-azurerm/blob/7f6e370fdce3c7e5ddca017a678d76cd3db99b88/azurerm/resource_arm_kubernetes_cluster.go#L133) is Computed, Optional, ForceNew and has no default.

In the case of https://github.com/pulumi/pulumi-aws/issues/451, the [property](https://github.com/terraform-providers/terraform-provider-aws/blob/03a8516d988de201ca3358f09b92a22f2507894d/aws/resource_aws_cloudformation_stack.go#L61) is Optional, ForceNew and has no default, *but also gets .Set* even though it is not marked as Computed.  I believe that if this gets fixed upstream to be marked `Computed`, it will fix the problem for Terraform, but not for Pulumi.

**Comment by lukehoban** [comment]
I suspect that https://github.com/pulumi/pulumi-gcp/issues/88 and https://github.com/pulumi/pulumi-gcp/issues/65 are also related to this.

**Comment by lukehoban** [comment]
This seems to be a widespread and critical issue.  Marking P1 in M22.

**Comment by lukehoban** [comment]
Confirmed that https://github.com/pulumi/pulumi-gcp/issues/65 is the same issue - the `region` property is what triggers the replacement (even though it wasn't changed) and it is marked `Computed`+`Optional`+`ForceNew`.

**Comment by pgavlin** [comment]
> I believe that if this gets fixed upstream to be marked Computed, it will fix the problem for Terraform, but not for Pulumi.

This turns out not to be the case. If I make exactly this fix locally, the diff changes from a `replace` to an `update`. There must be something more subtle going on here--I'll take a look at the GCP resources.

**Comment by pgavlin** [comment]
> Confirmed that pulumi/pulumi-gcp#65 is the same issue - the region property is what triggers the replacement (even though it wasn't changed) and it is marked Computed+Optional+ForceNew.

This issue turns out to be the same sort of TF bug as that present in the CF stack issue. Here's the schema for the relevant resource at the version `@pulumi/gcp` is locked to: 
https://github.com/terraform-providers/terraform-provider-google/blob/v1.20.0/google/resource_sql_database_instance.go#L58-L6

**Comment by pgavlin** [comment]
Indeed, here's the TF issue for 
https://github.com/pulumi/pulumi-gcp/issues/65: https://github.com/terraform-providers/terraform-provider-google/issues/2554

**Comment by pgavlin** [comment]
After investigating the resources mentioned in 
https://github.com/pulumi/pulumi-azure/issues/182, 
https://github.com/pulumi/pulumi-aws/issues/451, and 
https://github.com/pulumi/pulumi-gcp/issues/65, I do not believe that we have a bug here. All of these issues involved a resource with a field marked `Optional` and `ForceNew` that was written to by the TF provider. Two of these schemas were later amended to include a `Computed` annotation on the field at fault. The resources with the fixed schemas no longer exhibit this problem. The resource that does still have this issue--`aws.cloudformation.Stack`--no longer exhibits it if the `Computed` annotation is added.

**Comment by pgavlin** [comment]
For reference, here is a TF issue that describes the same behavior we saw in 
https://github.com/pulumi/pulumi-azure/issues/182:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/2114
