### ISSUE TITLE
Export synchronous versions of `get*` methods

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#387]
Today all Terraform DataSources are projected as asynchronous methods like `getSubnetIds(): Promise<Result>`.  This makes writing code against these APIs quite difficult, especially when they need to be used as inputs to control flow like loops.

We should also expose synchronous methods like `getSubnetIdsSync(): Result`.

We've experimented with use of the `deasync` JavaScript library to remove the fundamental asynchrony introduced by our RPC layer - and we could use this same approach more generally to solve this for all users.

**Comment by pgavlin** [comment]
This is done.
