### ISSUE TITLE
Treat terraform "sensitive" outputs as Pulumi secrets

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-terraform#406]
During a resource operation a provider is able to communicate information about outputs that should be persisted securely. These values are then treated as secrets by the rest of the system, which means they are encrypted before being stored in the Pulumi state file and the resulting `Output<T>`'s inside the language are also marked as secret.

Today, TF Bridges providers do not communicate back any information about what should be treated as a secret, but we can infer some of these values from the terraform schema, since they will be marked as sensitive.

We should update our logic such that we mark these values as secrets, when the engine supports them.

**Comment by lukehoban** [comment]
This issue presupposes that the Terrraform schema includes specification of "sensitive" outputs.  But as far as I can tell, there is no such thing.  There is https://www.terraform.io/docs/configuration/outputs.html#sensitive-suppressing-values-in-cli-output, but that is only for `output` blocks in terraform, not resource state, so is not what's needed here.

Is this issue not actionable?

If not - what should be done to make something like `Random` easier to use "safely"?

**Comment by pgavlin** [comment]
@lukehoban see https://github.com/hashicorp/terraform/blob/master/helper/schema/schema.go#L245-L249 for the definition of `Sensitive` in the TF schema package.

**Comment by lukehoban** [comment]
Indeed you are right!  Part of my confusion was that `Random` apparently doesn't use this - which is surprising as this is probably one of the primary source for generating sensitive values.   But great to see `Sensitive` is well-used in the AWS provider at least, so there is significant value here.

**Comment by pgavlin** [comment]
We could add our own overlays ala `AltTypes` for cases like Random if we feel it’s valuable enough.
