### ISSUE TITLE
Ability to run State Migrations / Change Resource IDs

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform#446]
As of v1.32.1 of the AzureRM Terraform provider, we are blocked on making any upgrades to the Terraform provider. This is because v1.32.1 introduced a StateMigration to the ID of Azure Table Storage

This migration completely changed the structure of the ID which means Pulumi is failing due to that ID change

A recreation of the issue can be seen in this video

https://asciinema.org/a/erl1cjoTadGxFN9OzVBNCSkgD

**Comment by ellismg** [comment]
We'll need to address this as part of M26 as it blocks our ability to ingest new versions of the AzureRM provider from upstream.

**Comment by stack72** [comment]
Closed via https://github.com/pulumi/pulumi/pull/3087
