### ISSUE TITLE
Python SDK versions are incompatible with other Pulumi Python SDKs

### ISSUE THREAD

**Issue by geekofalltrades** [pulumi/pulumi-terraform#502]
The v1.0.0 Python SDK requires `pulumi>=0.17.24,<0.18.0`: https://github.com/pulumi/pulumi-terraform/blob/v1.0.0/sdk/python/setup.py#L46

Other Pulumi SDKs that I'm working with in my project stack currently seem to require `pulumi>=1.0.0,<2.0.0`: https://github.com/pulumi/pulumi-kubernetes/blob/v1.2.0/sdk/python/setup.py#L34

This makes pulumi-terraform incompatible with the rest of my stack.

**Comment by stack72** [comment]
Apologies @geekofalltrades - fixing this up now!

**Comment by stack72** [comment]
@geekofalltrades version 1.1.0 has been released and will fix your issue - sorry about that!
