### ISSUE TITLE
Region is required though S3RemoteStateReferenceArgs says it's optional

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-terraform#507]
The interface for `S3RemoteStateReferenceArgs` says `region` is optional but then throws an error when it's not specified. 

https://github.com/pulumi/pulumi-terraform/blob/78e9371ad7724c45eba44bdf605d1e9ddc3aa111/sdk/nodejs/state/s3BackendConfig.ts#L37-L42

#### Code to Reproduce
```typescript
import * as terraform from "@pulumi/terraform";

export const remoteState = new terraform.state.RemoteStateReference("s3", {
    backendType: "s3",
    bucket: "my-bucket",
    key: "blah.tfstate",
});
```

#### Output
```
$ pulumi up
Previewing update (dev):

     Type                                     Name                       Plan       Info
 +   pulumi:pulumi:Stack                      pulumi-s3-remotestate-dev  create..   read terraform:state:RemoteStateReference s3
 +   pulumi:pulumi:Stack                      pulumi-s3-remotestate-dev  create     1 error
     └─ terraform:state:RemoteStateReference  s3                                    1 error

Diagnostics:
  pulumi:pulumi:Stack (pulumi-s3-remotestate-dev):
    error: preview failed

  terraform:state:RemoteStateReference (s3):
    error: Preview failed: error coercing config from Pulumi format to cty: attribute "region" is required

```

**Comment by stack72** [comment]
@clstokes this is optional in the same way that `accessKey` and `secretKey` are optional. If it's not specified, then it is read from EnvVar. This is the correct behaviour. If it were a required field, then it wouldn't read from EnvVar

Thoughts?

**Comment by clstokes** [comment]
@stack72 I see. That's a bit annoying because it requires extra configuration steps that the default aws provider doesn't require.

Mainly, for the default aws provider I just need to `pulumi config set aws:region us-west-2` for it to work, but for `RemoteStateReference`, I need to explicitly use `Config` to achieve the same thing. 

```
import * as terraform from "@pulumi/terraform";
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();

export const remoteState = new terraform.state.RemoteStateReference("s3", {
    backendType: "s3",
    bucket: "my-bucket",
    key: "blah.tfstate",

    region: config.require("aws:region"),
});
```

I understand why (`RemoteStateReference` isn't part of the aws provider), but it's not immediately obvious to the end user why this works differently.

I'll close this as there doesn't seem to be a necessary fix here.

**Comment by clstokes** [comment]
I didn't test the env var. I was expecting it to use the same config value
`aws:region` by default.

**Comment by lukehoban** [comment]
> I was expecting it to use the same config value `aws:region` by default.

That doesn’t sound quite right to me. That is reading a different providers config. And there is no great reason to believe that that value has any relationship to this provider or resource - especially in cases where first class providers are used for AWS so the `aws:region` config setting is not the real region being targeted in AWS. But also just because the remote state could very well be somewhere different.

I think the current behavior actually seems about right. But if we thought this was important to make externally configurable, I would expect it to be via configuration on the provider in question - like `terraform:awsRegion`
