### ISSUE TITLE
Design a better way to supply 'package names'

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-terraform#511]
Right now package names are all hardcoded in in lowercase in our resource packages.  i.e. 'elasticloadbalancingv2'.  This is fine for JS/Python, but is problematic for C# and other languages that want to do things like PascalCasing.  

https://github.com/pulumi/pulumi-terraform/pull/510

Provided a way for us to hack in the TitleCase names for these packages for C#.  However, we need a more generalized solution. Ideally one where the name can be provided once in an agnostic fashion, and each language can specify how to transform that name properly to their domain.  what might be best would be something like `Word_Separated_With_Underscores`.  This provides maximal information about what is actually a word boundary and each language can split that and combine appropriately.

**Comment by mikhailshilkov** [comment]
This has been addressed
