### ISSUE TITLE
Support statefiles generated by Terraform >v0.12.9

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-terraform#527]
When attempting to use a `terraform.state.RemoteStateReference` with a statefile created by a recent version of Terraform, I currently see this:

```
terraform:state:RemoteStateReference (other):
    error: Preview failed: error refreshing Terraform state: state snapshot was created by Terraform v0.12.23, which is newer than current v0.12.9; upgrade to Terraform v0.12.23 or greater to work with this state
 ```

We should update the version of Terraform that this provider links against to ensure it is compatible with the latest versions of Terraform.

Note that `v0.12.9` was released 9/17/2019, so is nearly 6 months old.

**Comment by stack72** [comment]
closed via #531
