### ISSUE TITLE
Upgrade to Terraform v0.12.29

### ISSUE THREAD

**Issue by startlabtech** [pulumi/pulumi-terraform#549]
Terraform v0.12.29 has been released, would be awesome for this to support that.

**Comment by lukehoban** [comment]
Yes - we should update this. Is there any particular capability that is blocked on this or issue you are seeing interoperating with newer terraform workspaces?

**Comment by startlabtech** [comment]
I am trying to use the RemoteState functionality and currently blocked as my terraform state is 0.12.29.
