### ISSUE TITLE
@pulumi/terraform: state snapshot was created by Terraform v0.13.0, which is newer than current v0.12.29

### ISSUE THREAD

**Issue by ctison** [pulumi/pulumi-terraform#556]
Tested with pulumi version `v2.9.0`
```json
  "dependencies": {
    "@pulumi/pulumi": "2.9.0",
    "@pulumi/terraform": "2.5.0"
  }
```

**Comment by stack72** [comment]
Hi @ctison 

I just cut pulumi-terraform v3.0.0 - this is based on v0.13.0 of Terraform and will fix up your issue

this should go through CI in the next 20 minutes or so

Please let me know if there are any issues

Paul
