### ISSUE TITLE
Does it possible release plugin compile with arch arm64 ?

### ISSUE THREAD

**Issue by adaam** [pulumi/pulumi-terraform#595]
Dear Developers,

I'm now use M1 as my primary laptop, when I want to deploy infra with Pulumi, it will show error

```
no resource plugin 'terraform-v4.5.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource terraform v4.5.0`
```

But when I ran the command, it will show
```
error: [resource plugin terraform-4.5.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-terraform-v4.5.0-darwin-arm64.tar.gz
```

Does it possible to compile this plugin with arch arm64 and place it to correct place?
If it's impossible, does somewhere document of how to build the plugin and put it to correct place to avoid this error message?

**Comment by stack72** [comment]
Hi @adaam 

Let me get that added for you!

Paul
