### ISSUE TITLE
terraform plugin not found for darwin-arm64

### ISSUE THREAD

**Issue by jvatic** [pulumi/pulumi-terraform#614]
When I try to use the [@pulumi/terraform](https://www.npmjs.com/package/@pulumi/terraform) package, I get an error when I run `pulumi preview` that the terraform plugin needs to be installed, and the command given to install it results in an HTTP fetch error.

This appears to be the same issue as in #595.

## Steps to reproduce

1. Use `@pulumi/terraform` in a pulumi TypeScript project to access outputs from terraform remote state stored in an S3 bucket.
2. See error that terraform plugin needs to be installed when running `pulumi preview`:
```
Diagnostics:
  pulumi:providers:terraform (default):
    error: no resource plugin 'terraform-v5.2.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource terraform v5.2.0`
```
3. Try to install the plugin, and get an HTTP fetch error:
```
[resource plugin terraform-5.2.0] installing
error: [resource plugin terraform-5.2.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-terraform-v5.2.0-darwin-arm64.tar.gz
```

Expected: The plugin would install and I would be able to run `pulumi preview`
Actual: I get an HTTP fetch error

Additional info: I'm using an M1 Mac, and the plugin appears to exist for `darwin-amd64`:
```
$ curl -I https://get.pulumi.com/releases/plugins/pulumi-resource-terraform-v4.5.0-darwin-amd64.tar.gz
HTTP/2 200
...
```

**Comment by stack72** [comment]
Hi @jvatic 

I released v5.2.1 which has the new darwin arm64 build :)

Paul
