### ISSUE TITLE
Bump to the latest Terraform release

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-terraform#62]
This is a standing work item as a reminder to consider bumping to the latest Terraform release each milestone.  We may decide not to -- if, say, a release needs more bake time -- but at least we will have this work item as a reminder.  This includes not just this repo, but any other downstream repos that may have locked to a specific version in the `Gopkg.toml` file.

**Comment by jen20** [comment]
I think we can close this out, since the version of Terraform used depends on the version on which specific providers depend. `govendor-override` ensures that where possible the dependency versions match the provider.
